# ┌────────────────────────────────────────────────────────────────────────┐
# │                               chatbot.py                               │
# │               Conversational Memory & Persistence Engine               │
# └────────────────────────────────────────────────────────────────────────┘
"""
This module implements the primary conversational memory architectures for the KAYRA assistant.
It features a dual-tier memory system comprising:
- A sliding short-term memory window representing the most recent interactions in the session.
- A persistent long-term memory database backed by transactional, corruption-resistant storage.
"""

import os
from dotenv import dotenv_values

# Robust imports supporting relative paths across all execution contexts
# Fallbacks are configured to handle standalone execution vs imported module contexts cleanly.
try:
    from .llm_engine import CentralizedLLMEngine
except ImportError:
    try:
        from modules.llm_engine import CentralizedLLMEngine
    except ImportError:
        from llm_engine import CentralizedLLMEngine

try:
    from .utils import (
        print_banner, print_info, print_success, print_warning, print_error, print_system, console,
        load_conversation_memory, save_conversation_memory, answer_modifier, real_time_info,
        SentenceStreamer,
    )
except ImportError:
    try:
        from modules.utils import (
            print_banner, print_info, print_success, print_warning, print_error, print_system, console,
            load_conversation_memory, save_conversation_memory, answer_modifier, real_time_info,
            SentenceStreamer,
        )
    except ImportError:
        from utils import (
            print_banner, print_info, print_success, print_warning, print_error, print_system, console,
            load_conversation_memory, save_conversation_memory, answer_modifier, real_time_info,
            SentenceStreamer,
        )


# ┌────────────────────────────────────────────────────────────────────────┐
# │                            CONFIGURATION                               │
# └────────────────────────────────────────────────────────────────────────┘

# Load environment configuration parameters from active profile
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env_vars = dotenv_values(os.path.join(root, ".env")) or {}
assistant_name = env_vars.get("ASSISTANT_NAME", "").strip()
if not assistant_name:
    assistant_name = "Kayra"

# Access the centralized mode-switching infrastructure broker (offline Kokoro / online cloud endpoints)
engine = CentralizedLLMEngine()

# Memory persistence, response cleanup, and temporal-context helpers now live in modules/utils.py
# (previously duplicated near-verbatim across chatbot.py / real_time_search.py).
AnswerModifier = answer_modifier
RealTimeInformation = real_time_info

# ┌────────────────────────────────────────────────────────────────────────┐
# │                     MEMORY SPACE INITIALIZATION                        │
# └────────────────────────────────────────────────────────────────────────┘

# Long-term data tables pulled from disk. Contains selectively saved/remembered dialogue frames.
permanent_memory = load_conversation_memory()

# Volatile processing RAM buffer. Acts as a short-term sliding context window for the current session.
session_memory = []

# ┌────────────────────────────────────────────────────────────────────────┐
# │                       MAIN INTERACTION PIPELINE                        │
# └────────────────────────────────────────────────────────────────────────┘

def Chatbot(query, tts_engine=None, mood=None):
    """
    Orchestrates the conversational memory tree window, structures payload contexts,
    and returns token response generation patterns natively via the central engine pipeline.

    Memory Context Hierarchy Injection Sequence:
        1. Renders the dynamic System Identity Prompt + Temporal Environment metrics.
        2. Appends historical Long-Term context frames (loaded dynamically from disk).
        3. Appends the Short-Term volatile sliding window session context (bounded to the last 6 messages).
        4. Appends the active target User Query.

    Args:
        query (str): The raw text input spoken or typed by the user.
        tts_engine: Optional TTS engine instance to enable live audio streaming.
        mood (str): Optional detected user mood (from SemanticEmotionEngine) used to steer
                    the assistant's tone for this turn.

    Returns:
        str: The full, normalized text response generated by the LLM pipeline.
    """
    global permanent_memory, session_memory

    try:
        # Real-time speech streaming.
        #
        # There is deliberately NO private queue/worker thread here any more. The TTS
        # engine owns a single cancellable pipeline (text queue -> synthesis -> playback),
        # so `tts_engine.speak()` returns immediately and a barge-in drops pending
        # sentences, in-flight synthesis and buffered audio in one atomic step. The old
        # local worker kept its own backlog that survived `tts.stop()`, which is why an
        # interrupted answer used to carry on talking sentence after sentence.
        streamer = None
        if tts_engine:
            # Capture this turn's token once. Checking the token (rather than the global
            # `interrupted` flag) means nothing else clearing that flag — a proactive
            # suggestion calling begin_turn(), say — can resurrect a response the user
            # already interrupted.
            turn_token = tts_engine.turn_token()
            streamer = SentenceStreamer(
                tts_engine.speak,
                stop_check=lambda: tts_engine.is_cancelled(turn_token),
            )

        # 1. Fetch current identity alignment conditions (forces strict behavior directives)
        identity_prompt = engine.get_identity_prompt(mood=mood)

        # Compile base system payload context
        api_messages = [
            {"role": "system", "content": identity_prompt + "\n\n" + RealTimeInformation()}
        ]

        # 2. Append permanent storage context tracking frames (if any exist)
        if len(permanent_memory) > 0:
            for msg in permanent_memory:
                api_messages.append(msg)
        
        # 3. Append volatile sliding window session layers (bounded to the last 6 iterations to protect token context limit)
        recent_session = session_memory[-6:]
        for msg in recent_session:
            api_messages.append(msg)
        
        # 4. Attach raw target user query block
        api_messages.append({"role": "user", "content": query})

        response_text = ""
        console.print("\n[bold white]Streaming Response Live:[/bold white] ", end="")

        # 5. Interface with the auto-switching engine streaming chunk generator channels
        for chunk in engine.generate_chat_stream(api_messages):
            console.print(chunk, end="", style="italic green")
            response_text += chunk

            if streamer:
                streamer.feed(chunk)
                if tts_engine.is_cancelled(turn_token):
                    # The user barged in. Stop pulling tokens: continuing would burn quota
                    # on an answer nobody is listening to, and every sentence produced from
                    # here on could only ever arrive after the interruption.
                    print_system("Response cancelled by user interruption.")
                    break

        # Flush the trailing partial sentence
        if streamer:
            streamer.flush()

        console.print("\n")

        # 6. Normalize string layouts by removing redundant newline separations
        response_text = AnswerModifier(response_text)

        # 7. Index original input string and pure string response to the sliding short-term cache
        session_memory.append({"role": "user", "content": query})
        session_memory.append({"role": "assistant", "content": response_text})

        # 8. Evaluation loop processing explicit long-term indexing criteria commands.
        # If the user explicitly asks to memorize this exchange, we permanently write it to our local JSON database.
        triggers = ["store this", "remember this", "save this", "memorize this", "note this"]

        if any(trigger in query.lower() for trigger in triggers):
            permanent_memory.append({"role": "user", "content": query})
            permanent_memory.append({"role": "assistant", "content": response_text})

            # Execute transactional commit to disk
            if save_conversation_memory(permanent_memory):
                print_success(f"Secure context verified. Stored in {assistant_name} structural database.")
        
        return response_text


    except Exception as e:
        print_error(f"Pipeline failure processing active transaction: {e}")
        return ""

# ┌────────────────────────────────────────────────────────────────────────┐
# │                     DIAGNOSTIC TEST RUNTIME BLOCK                      │
# └────────────────────────────────────────────────────────────────────────┘

if __name__ == "__main__":
    # Boot the chatbot playground with the unified cyberpunk banner and config notifications
    print_banner("KAYRA CHATBOT ENGINE", f"Interactive {assistant_name} Conversational Sandbox")
    print_success(f"Conversational Node Online. Saved Memory Index Items: {len(permanent_memory)}")
    
    while True:
        try:
            # Capture user query utilizing rich-enabled premium terminal input prompt
            user_query = console.input("[bold magenta]User >[/bold magenta] ").strip()
            
            if not user_query.strip():
                continue

            if user_query.lower() in ["exit", "quit", "bye"]:
                print_system("Closing modular context workspace. Systems offline.")
                break
            
            Chatbot(user_query)

        except KeyboardInterrupt:
            # Handle terminal interrupts gracefully
            console.print()
            print_system("Terminal Halt Event Intercepted. Shutting down chatbot.")
            break